# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyaccountant', '0004_auto_20170717_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='currency',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
