# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyaccountant', '0007_auto_20170726_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='group',
        ),
        migrations.DeleteModel(
            name='AccountType',
        ),
        migrations.DeleteModel(
            name='CategoryGroup',
        ),
    ]
