# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyaccountant', '0009_importfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('headers', models.BooleanField()),
            ],
        ),
    ]
