# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyaccountant', '0014_auto_20170812_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('recurrence', models.IntegerField(choices=[(1, 'Weekly'), (2, 'Monthly'), (3, 'Yearly')])),
            ],
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-show_on_dashboard', 'name']},
        ),
        migrations.AlterField(
            model_name='account',
            name='show_on_dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='dst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opposing_recurring_transactions', to='pyaccountant.Account'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='src',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyaccountant.Account'),
        ),
        migrations.AddField(
            model_name='transactionjournal',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pyaccountant.RecurringTransaction'),
        ),
    ]
