# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyaccountant', '0016_auto_20170812_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionjournal',
            old_name='bill',
            new_name='recurrence',
        ),
    ]
