# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 20:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('internal_type', models.IntegerField(choices=[(1, 'Personal'), (2, 'Revenue'), (3, 'Expense'), (4, 'System')], default=1)),
                ('active', models.BooleanField(default=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('show_on_dashboard', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-show_on_dashboard', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ImportConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('headers', models.BooleanField(help_text='First line contains headers')),
                ('config', models.TextField()),
                ('default_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='silverstrike.Account')),
            ],
        ),
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='imports')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('recurrence', models.IntegerField(choices=[(1, 'Weekly'), (2, 'Monthly'), (3, 'Yearly')])),
                ('transaction_type', models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawl'), (3, 'Transfer')])),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opposing_recurring_transactions', to='silverstrike.Account')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silverstrike.Account')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silverstrike.Account')),
            ],
            options={
                'ordering': ['-journal__date', 'journal__title'],
            },
        ),
        migrations.CreateModel(
            name='TransactionJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawl'), (3, 'Transfer'), (4, 'SYSTEM')])),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='silverstrike.Category')),
                ('recurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='silverstrike.RecurringTransaction')),
            ],
            options={
                'ordering': ['-date', 'title'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silverstrike.TransactionJournal'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='opposing_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opposing_transactions', to='silverstrike.Account'),
        ),
    ]
