# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='internal_type',
            new_name='account_type',
        ),
    ]
