# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('name', 'account_type')]),
        ),
    ]
