# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyaccountant', '0002_auto_20170710_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='opposing_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='opposing_transactions', to='pyaccountant.Account'),
            preserve_default=False,
        ),
    ]
