# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 16:38
from __future__ import unicode_literals

from django.db import migrations


def update_account_types(apps, schema_editor):
    Account = apps.get_model('silverstrike', 'Account')
    Account.objects.filter(account_type=3).update(account_type=2)
    Account.objects.filter(account_type=4).update(account_type=3)


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0003_auto_20170823_1623'),
    ]

    operations = [
        migrations.RunPython(update_account_types),
    ]
