# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0004_auto_20170828_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.IntegerField(choices=[(1, 'Personal'), (2, 'Foreign'), (3, 'System')], default=1),
        ),
        migrations.AlterField(
            model_name='transactionjournal',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawl'), (3, 'Transfer'), (4, 'Reconcile')]),
        ),
    ]
