# Generated by Django 2.1.2 on 2018-10-25 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0004_auto_20180203_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='last_weekday_in_month',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='skip',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='weekend_handling',
            field=models.IntegerField(choices=[(0, 'Same day'), (1, 'Previous weekday'), (2, 'Next weekday')], default=0),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='recurrence',
            field=models.IntegerField(choices=[(0, 'Disabled'), (1, 'Monthly'), (2, 'Quarterly'), (3, 'Biannually'), (4, 'Annually'), (5, 'Weekly')]),
        ),
    ]
