# Generated by Django 2.1.2 on 2018-12-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0005_auto_20180929_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='recurringtransaction',
            old_name='recurrence',
            new_name='interval'
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='multiplier',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='usual_month_day',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='weekend_handling',
            field=models.IntegerField(choices=[(3, 'Skip recurrence'), (0, 'Same day'), (1, 'Previous weekday'), (2, 'Next weekday')], default=0),
        ),
    ]
