# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyaccountant', '0005_auto_20170726_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='category',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='categorygroup',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transactionjournal',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
