# Generated by Django 2.0.1 on 2018-03-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0005_auto_20180320_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='name',
            field=models.CharField(default='Household', max_length=64),
            preserve_default=False,
        ),
    ]
