# Generated by Django 2.1.2 on 2018-10-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0005_auto_20180929_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='last_day_in_month',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='skip',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='weekend_handling',
            field=models.IntegerField(choices=[(3, 'Skip recurrence'), (0, 'Same day'), (1, 'Previous weekday'), (2, 'Next weekday')], default=0),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='recurrence',
            field=models.IntegerField(choices=[(0, 'Disabled'), (1, 'Monthly'), (2, 'Quarterly'), (3, 'Biannually'), (4, 'Annually'), (5, 'Weekly'), (6, 'Daily')]),
        ),
    ]
