# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyaccountant', '0006_auto_20170726_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionjournal',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawl'), (3, 'Transfer'), (4, 'SYSTEM')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
