# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0006_auto_20170904_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='opposing_account',
        ),
        migrations.RemoveField(
            model_name='transactionjournal',
            name='category',
        ),
        migrations.RemoveField(
            model_name='transactionjournal',
            name='recurrence',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='TransactionJournal',
        ),
    ]
