# Generated by Django 2.0.1 on 2018-03-20 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0006_household_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='household',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='silverstrike.HouseHold'),
            preserve_default=False,
        ),
    ]
