# Generated by Django 2.1.2 on 2018-10-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0006_auto_20181025_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurringtransaction',
            old_name='recurrence',
            new_name='interval'
        )
    ]
