# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0007_auto_20170904_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='split',
            options={'ordering': ['-date', 'journal', 'description']},
        ),
        migrations.AddField(
            model_name='journal',
            name='recurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrences', to='silverstrike.RecurringTransaction'),
        ),
    ]
