# Generated by Django 2.1.3 on 2018-11-27 19:35

from django.db import migrations


def recurrences(apps, schema_editor):
    RecurringTransaction = apps.get_model('silverstrike', 'RecurringTransaction')
    RecurringSplit = apps.get_model('silverstrike', 'RecurringSplit')
    for recurrence in RecurringTransaction.objects.all():
        RecurringSplit.objects.create(transaction=recurrence, amount=recurrence.amount,
                                      account=recurrence.dst, opposing_account=recurrence.src,
                                      date=recurrence.next_date, title=recurrence.title,
                                      category=recurrence.category)
        RecurringSplit.objects.create(transaction=recurrence, amount=-recurrence.amount,                                        account=recurrence.src, opposing_account=recurrence.dst,
                                      date=recurrence.date, title=recurrence.title,
                                      category=recurrence.category)


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0007_auto_20181127_1931'),
    ]

    operations = [
        migrations.RunPython(recurrences),
    ]
