# Generated by Django 2.1.2 on 2018-10-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0007_auto_20181027_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='last_day_in_month',
        ),
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='skip',
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='multiplier',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='interval',
            field=models.IntegerField(choices=[(0, 'Disabled'), (1, 'Monthly same date'), (7, 'Monthly (last day)'), (2, 'Quarterly'), (3, 'Biannually'), (4, 'Annually'), (5, 'Weekly'), (6, 'Daily')]),
        ),
    ]
