# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pyaccountant', '0008_auto_20170809_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='imports')),
            ],
        ),
    ]
