# Generated by Django 2.1.5 on 2019-02-04 19:25

from django.db import migrations, models


def set_ibans(apps, schema_editor):
    Account = apps.get_model('silverstrike', 'Account')
    db_alias = schema_editor.connection.alias
    for a in Account.objects.using(db_alias).exclude(iban=''):
        a.import_ibans = '["{}"]'.format(a.iban)
        a.save()


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0008_auto_20190105_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='import_ibans',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='account',
            name='import_names',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'Transfer')]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'Transfer'), (4, 'Reconcile')]),
        ),
        migrations.RunPython(set_ibans)
    ]
