# Generated by Django 2.1.2 on 2018-11-17 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0008_auto_20181027_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='recurringtransaction',
            options={'ordering': ['next_date']},
        ),
        migrations.RenameField(
            model_name='recurringtransaction',
            old_name='date',
            new_name='next_date',
        ),
    ]
