# Generated by Django 2.1.3 on 2018-11-27 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0008_auto_20181127_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='dst',
        ),
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='src',
        ),
    ]
