# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0008_auto_20170906_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='split',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='silverstrike.Journal'),
        ),
    ]
