# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0009_auto_20170906_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='silverstrike.Category'),
        ),
    ]
