# Generated by Django 2.1.2 on 2018-12-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0009_auto_20181117_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringtransaction',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='recurringtransaction',
            old_name='next_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='usual_month_day',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='interval',
            field=models.IntegerField(choices=[(0, 'Disabled'), (6, 'Daily'), (5, 'Weekly'), (1, 'Monthly'), (2, 'Quarterly'), (3, 'Biannually'), (4, 'Anually')]),
        ),
    ]
