# Generated by Django 2.1.3 on 2018-11-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0009_auto_20181127_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='last_day_in_month',
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='multiplier',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
