# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0010_recurringtransaction_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='split',
            options={'ordering': ['-date', 'description']},
        ),
        migrations.AlterField(
            model_name='split',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='silverstrike.Category'),
        ),
    ]
