# Generated by Django 2.1.3 on 2018-11-30 01:18

from django.db import migrations


def skip_to_multiplier(apps, schema_editor):
    RecurringTransaction = apps.get_model('silverstrike', 'RecurringTransaction')
    for recurrence in RecurringTransaction.objects.all():
        recurrence.multiplier = recurrence.skip + 1


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0010_auto_20181130_0110'),
    ]

    operations = [
        migrations.RunPython(skip_to_multiplier),
    ]
