# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyaccountant', '0010_importconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='importconfiguration',
            name='default_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pyaccountant.Account'),
        ),
    ]
