# Generated by Django 2.1.3 on 2018-11-30 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0011_auto_20181130_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='skip',
        ),
        migrations.RenameField(
            model_name='recurringtransaction',
            old_name='recurrence',
            new_name='interval'
        ),
    ]
