# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0011_auto_20170926_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='split',
            options={'ordering': ['-date', 'title']},
        ),
        migrations.RenameField(
            model_name='split',
            old_name='description',
            new_name='title',
        ),
    ]
