# Generated by Django 2.1.3 on 2018-11-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0012_auto_20181130_0126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='interval',
            field=models.IntegerField(choices=[(0, 'Disabled'), (1, 'Monthly same date'), (7, 'Monthly (last day)'), (2, 'Quarterly'), (3, 'Biannually'), (4, 'Annually'), (5, 'Weekly'), (6, 'Daily')]),
        ),
    ]
