# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyaccountant', '0012_auto_20170811_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='importconfiguration',
            name='config',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='importconfiguration',
            name='headers',
            field=models.BooleanField(help_text='First line contains headers'),
        ),
        migrations.AlterField(
            model_name='importconfiguration',
            name='name',
            field=models.CharField(default='asdf', max_length=64),
            preserve_default=False,
        ),
    ]
