# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0013_auto_20170928_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='split',
            old_name='journal',
            new_name='transaction',
        ),
    ]
