# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0014_auto_20170928_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='importconfiguration',
            name='dateformat',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
