# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyaccountant', '0015_auto_20170812_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='recurringtransaction',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-journal__date', 'journal__title']},
        ),
        migrations.AlterModelOptions(
            name='transactionjournal',
            options={'ordering': ['-date', 'title']},
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawl'), (3, 'Transfer')], default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactionjournal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='pyaccountant.Category'),
        ),
    ]
