# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0017_budget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-active', 'name']},
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.IntegerField(choices=[(1, 'Personal'), (2, 'Revenue'), (3, 'Expense'), (4, 'System'), (5, 'Foreign')], default=1),
        ),
    ]
