# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 23:28
from __future__ import unicode_literals

from django.db import migrations


def migrate_to_foreign_accounts(apps, schema_editor):
    Account = apps.get_model('silverstrike', 'Account')
    Account.objects.filter(account_type=2).update(account_type=5)
    Account.objects.filter(account_type=3).update(account_type=5)


class Migration(migrations.Migration):

    dependencies = [
        ('silverstrike', '0018_auto_20171115_2327'),
    ]

    operations = [
        migrations.RunPython(migrate_to_foreign_accounts),
    ]
